"use client";
import {FormEvent,useEffect,useState} from "react";
import Link from "next/link";
import {createSupabaseBrowserClient} from "@/lib/supabase/browser";
export default function ResetPasswordPage(){
const[password,setPassword]=useState("");const[confirm,setConfirm]=useState("");const[ready,setReady]=useState(false);const[busy,setBusy]=useState(false);const[message,setMessage]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);
useEffect(()=>{let active=true;const supabase=createSupabaseBrowserClient();supabase.auth.getSession().then(({data})=>{if(active)setReady(!!data.session)}).catch(()=>{if(active)setReady(false)});return()=>{active=false}},[]);
async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError(null);setMessage(null);if(password!==confirm){setError("Adgangskoderne er ikke ens.");return}if(!ready){setError("Linket er udløbet eller ugyldigt. Bestil et nyt.");return}setBusy(true);try{const supabase=createSupabaseBrowserClient();const{error:updateError}=await supabase.auth.updateUser({password});if(updateError)throw updateError;setMessage("Din adgangskode er ændret. Du kan nu logge ind.");setPassword("");setConfirm("");await supabase.auth.signOut()}catch(cause){setError(cause instanceof Error?cause.message:"Adgangskoden kunne ikke ændres.")}finally{setBusy(false)}}
return <main className="auth"><section className="auth-card"><div className="auth-brand">Gainora<span>.</span></div><h1>Vælg ny adgangskode</h1>{!ready?<p className="muted">Åbn linket fra din nulstillingsmail. <Link href="/forgot-password">Bestil nyt link</Link></p>:<form onSubmit={submit}><label className="field">Ny adgangskode<input type="password" autoComplete="new-password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)} required/></label><label className="field">Gentag adgangskode<input type="password" autoComplete="new-password" minLength={10} value={confirm} onChange={e=>setConfirm(e.target.value)} required/></label><button type="submit" disabled={busy}>{busy?"Gemmer...":"Skift adgangskode"}</button></form>}{error?<p role="alert" style={{color:"var(--bad)"}}>{error}</p>:null}{message?<p role="status">{message}</p>:null}<p><Link href="/login">Til login</Link></p></section></main>}
